### ISSUE TITLE
[Firefox for Android Fenix + Gboard] Holding down the Backspace button, removes text both before and after the cursor

### ISSUE THREAD

**Issue by DandelionSprout** [codemirror/CodeMirror#6777]
As can hopefully be seen in the below video, textboxes that utilise CodeMirror, have a major problem when using Firefox for Android Fenix along with Gboard, wherein holding down Backspace removes text both before and after the cursor. If the cursor is placed halfway into a line, then the time it takes to remove the 50% of text that is before the cursor, will also have removed circa 15% of the text that is after the cursor. This can hopefully be seen in the video below: 

https://user-images.githubusercontent.com/22780683/132951963-c4bd81e7-f943-4e65-8357-3f4347a144ff.mp4

This affects uBlock Origin in particular, who use CodeMirror as its sole textbox engine.

• Example URL: `moz-extension://13c4bc4f-395b-4a46-8ac9-8ba82bcc233c/dashboard.html#1p-filters.html` (Requires having uBlock Origin installed). I was also able to replicate this on a much smaller scale at the "This is CodeMirror" preview on `https://codemirror.net/`
• Browser: Firefox Nightly for Android 94.0a1 (Build `#`2015833131)
• OS: Android 10 aarch64
• Unit: Motorola One Zoom
• Keyboard app: Gboard 10.8.05.382062350-release-arm64-v8a

I was pointed towards here from https://github.com/uBlockOrigin/uBlock-issues/issues/1716.

**Comment by gorhill** [comment]
No need to install an extension, the issue can be reproduced using a CodeMirror demo: <https://codemirror.net/demo/complete.html>.

**Comment by marijnh** [comment]
Hi. Thanks for the report. There's no active work happening on CodeMirror 5.x's mobile backend though, and Firefox Android is not a major target, so this is unlikely to get addressed in the near future. CodeMirror 6 should work a lot better on mobile devices, but I can imagine it'll be a while before systems like uBlock switch over.

**Comment by krystian3w** [comment]
Samsung keyboard is also broken

**Comment by Poopooracoocoo** [comment]
This could be an instance of https://github.com/mozilla-mobile/fenix/issues/4208. Mozilla has resolved a bunch of typing related issues over Fenix's three years but lots of issues remain. You could comment there or make a new issue on their repo :)
