### ISSUE TITLE
Paste by using middle click in firefox not working

### ISSUE THREAD

**Issue by aeng** [codemirror/CodeMirror#931]
Middle click to paste text in CodeMirror2 doesn't work in Firefox browser but works in Chrome.

**Comment by lilydjwg** [comment]
Instead of patching Firefox, I guess an extension may work.

**Comment by frostyfrog** [comment]
Since no one has linked to it already, [here][ffbug] is the relevant bug within Firefox's Bugzilla. It looks like there are options that currently work in the developer edition of Firefox (I tried the first provided example, turned the &lt;p&gt; element into a &lt;textarea&gt; and the code worked). It appears that the FF team are still trying to make sure that the clipboard API standard gets nailed down first before this will get fixed in CodeMirror.

[ffbug]: https://bugzilla.mozilla.org/show_bug.cgi?id=846674

**Comment by frabjous** [comment]
The bug in Firefox's Bugzilla linked to by frostyfrog was marked as resolved about a month ago, but the problem persists for codemirror. Any progress on this?

**Comment by marijnh** [comment]
Not sure what they are supposed to have fixed there, but in Firefox nightly there's still no paste event for middle-click pasting.

**Comment by frabjous** [comment]
The following minimal HTML will fire the onpaste event  in Firefox 55 (linux) with a middle click:

```
<html>
<body>
<div id="editable" width="100%" contenteditable onpaste="alert('you pasted');" >
  Middle click here
</div>
</body>
</html>
```
It also works on textareas, etc., even without the contenteditable attribute.

I can't figure out how to make that work for codeMirror, however, if it is possible.

**Comment by frabjous** [comment]
Middle click works fine to paste in Firefox with the similar EditArea javascript editor -- [Example here.](http://www.cdolivet.com/editarea/editarea/exemples/exemple_full.html) How did they manage it?

**Comment by lilydjwg** [comment]
@frabjous it's a big textarea, with all normal features like GTK editing keys available. The colorful text is laid under it.

**Comment by nthiery** [comment]
A fix would be most welcome, e.g. for our teaching with Jupyter under linux.

Thanks in advance!

**Comment by lilydjwg** [comment]
I'm annoyed by Jupyter not supporting middle-click paste just yesterday....There is no way to copy a value from output to the input without this feature when I've mapped Ctrl-C to interrupt the kernel instead.

**Comment by simcop2387** [comment]
Wanted to chime in that there's also a related Firefox bug ticket open about this issue too.  https://bugzilla.mozilla.org/show_bug.cgi?id=953389

**Comment by suvayu** [comment]
The original FF (issue)[https://bugzilla.mozilla.org/show_bug.cgi?id=846674] has been resolved.  Does this mean we can have this fixed?  I'm using Jupyter, and middle click not working severely limits my productivity.

**Comment by marijnh** [comment]
I'm still not seeing any paste events generated for middle clicks on uneditable elements in Firefox 59, so no, I guess the functionality we need to make this work still isn't there.

**Comment by suvayu** [comment]
Hi @marijnh, I can middle click paste pretty much everywhere in FF on a wide range of websites.  Could you be a bit more specific (sorry, I'm not a web developer).  Maybe I could help test and narrow down the exact issue?

PS: the latest release is [FF 60](https://www.mozilla.org/en-US/firefox/60.0/releasenotes/).

**Comment by marijnh** [comment]
The thing that looks editable in CodeMirror isn't actually editable on the HTML level (it's static content, and focus is put on a hidden textarea), so Firefox doesn't understand that it should allow paste when this element is middle-clicked and doesn't generate the events necessary to access the clipboard.

**Comment by suvayu** [comment]
Hi @marijnh, I had a look at the generated html. I'm not sure how to reproduce a minimal example so that I can file a bug report on the FF bugzilla. I feel waiting for the issue to be fixed without a specific bug report on the FF bugzilla isn't going to help the situation. I would be happy to file the report, and follow up, if you could help me create a minimal example.

Thanks

**Comment by marijnh** [comment]
Minimal example: an empty document with a `paste` handler registered on the body. In Chrome, if you middle-click on the document the paste handler fires and can move focus to, say, a textarea to intercept the paste. In Firefox, it nothing happens.

**Comment by suvayu** [comment]
Hi @marijnh, sorry to repeat myself.  I am not a web developer (only good with languages like Python, C++, etc), and don't know how to create an example from your description of the issue. Could you please help with a code snippet I could work with?

**Comment by suvayu** [comment]
Okay, perfect!  Now I'll follow up with the FF bugzilla.  Is this the correct place to report any progress, or should I open a new issue?

**Comment by suvayu** [comment]
You can find the new bug report [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1461708).

Cheers,

**Comment by frabjous** [comment]
Incidentally, with the following small changes to the mwe, it already works in firefox:
~~~~
<!DOCTYPE html>
<html>
<meta charset="utf-8" />
<title>Test paste events</title>
<body contenteditable>
</body>
<script type="text/javascript">
<!--
  document.onpaste = function(e) {
    const p = document.createElement('p')
    p.textContent = "You've pasted something of types " + e.clipboardData.types
    document.body.appendChild(p)
    return false;
  }
//-->
</script>
</html>
~~~~

That is, adding the "contenteditable" flag to the body tag makes it generate the events. The return false at the end of the function prevents it from actually pasting in the contents, as it normally would.

I have no idea if these changes are compatible with the rest of codemirror's codebase.

**Comment by marijnh** [comment]
See the [`inputStyle` option](http://codemirror.net/doc/manual.html#option_inputStyle), but that is unfortunately not very solid yet. There are plans to rewrite the library to work with contentEditable from the base up, which would sidestep such issues, but it's not clear yet how and when that will really happen.

**Comment by adrianheine** [comment]
This is a issue that's difficult if not impossible to solve with the fundamental approach currently taken by CodeMirror.

We are working on a rewrite (CodeMirror 6) that will address this issue, and we are currently raising money for this work: See [the announcement](https://codemirror.net/6/) for more information about the rewrite and a demo.

Note that CodeMirror 6 is by no means stable or usable in production, yet. It's highly unlikely that we pick up this issue for CodeMirror 5, though.

**Comment by nchevobbe** [comment]
Hello there, I'm currently monkey-patching the codeMirror version we use in Firefox DevTools, and everything seems to work fine (using `dispatchEvent` instead of focusing the input on scroller's `paste`).
Could someone assign me the bug? I'll open a PR shortly.

**Comment by marijnh** [comment]
Apparently not, github won't let me assign this to you (I guess you can only assign team members?). But don't let that stop you!

**Comment by nchevobbe** [comment]
I won't :) PR's coming up

**Comment by marijnh** [comment]
This was finally fixed in #5751 (but see also #5754 )

**Comment by cu** [comment]
I think this might need to be reopened; I can't middle-click to paste on any of the demos of the codemirror.net site with Firefox 76.0 on Ubuntu 19.10.

Perhaps worth noting that it _does_ appear to work on the CM6 demo site.

**Comment by marijnh** [comment]
It still works for me (Firefox 75 and 76 on Debian)...

**Comment by dmitry-at-publons** [comment]
Trying demos on codemirror.net with Firefox 76.0.1 on Ubuntu 18.04: can *paste*, but can't *copy* by selecting or double clicking.

**Comment by lilydjwg** [comment]
And it pastes the _clipboard_ selection, not the _primary_ selection as native applications do.

**Comment by nchevobbe** [comment]
> Trying demos on codemirror.net with Firefox 76.0.1 on Ubuntu 18.04: can _paste_, but can't _copy_ by selecting or double clicking.
> 
> Same behaviour on https://codemirror.net/6/.

Yes, this is a known issue on the Firefox side: https://bugzilla.mozilla.org/show_bug.cgi?id=1593761
